### ISSUE TITLE
License is MIT while source says BSD3

### ISSUE THREAD

**Issue by juhp** [yav/pretty-show#12]
There seems to be an inconsistency in the LICENSE file (MIT) and license stated in the source files (BSD).  MIT and BSD are separate and different licenses.

Which is the correct intended license? :)

Thanks for developing pretty-show

**Comment by mathstuf** [comment]
Looking at the git blame, it appears that the LICENSE file was copied from another project since it has a date of 2008 while the import was in 2009. Though it is possible the code is older than the git history too, but judging by the contents of the commit, that is unlikely.

**Comment by yav** [comment]
Thanks for pointing this out!   I've corrected the Cabal file to indicate that we are using the MIT license.

**Comment by juhp** [comment]
Thanks - it would be nice to update the headers in Pretty.hs and Value.hs then also to state MIT.

**Comment by juhp** [comment]
Thanks again
