### ISSUE TITLE
Need to ask for more instances than you'd think

### ISSUE THREAD

**Issue by gitfoxi** [yav/pretty-show#15]
I'm not sure whether this can be better but I have to ask for instances like:

```
instance PrettyVal A
instance PrettyVal a => PrettyVal (Maybe a)
instance PrettyVal Bool
instance PrettyVal B
```

When I only want to print B which is something like:

```
data A = A
 deriving (Show, Generic)

data B = B
 { a :: A
 , mis :: Maybe [Integer]
 , b :: Bool
 }
 deriving (Show, Generic)
```

**Comment by yav** [comment]
Hi,
could you say a bit more about what the issue?  I am not sure I understand the problem as yet.  Generally, if you stick to standard `Show` instances you shouldn't need to use `PrettyVal` at all.
