### ISSUE TITLE
pretty-show-1.6.10 build failure with GHC 7.10.2 and happy-1.18.9

### ISSUE THREAD

**Issue by peti** [yav/pretty-show#19]
I tried to compile a project of mine on Travis-CI with GHC 7.10.2 and the build ended up failing during the build of pretty-show: https://travis-ci.org/NixOS/cabal2nix/jobs/137826448#L1012. I'm not sure what to make of this, especially since other compiler versions don't seem to have this issue. Do you have any idea what might cause this error?

**Comment by danr** [comment]
The `happy` version used is too old. I don't know exactly what version is needed, but the one that's used in the build is not aware of unboxed booleans, https://ghc.haskell.org/trac/ghc/ticket/6135

**Comment by peti** [comment]
OK, thanks for the quick response!
