### ISSUE TITLE
Failure to build when installing a dependant package.

### ISSUE THREAD

**Issue by julialongtin** [yav/pretty-show#30]
new system, nothing in ~/.ghc or ~/cabal
cabal update
cabal install accelerate-llvm-native
-- installs a whole bunch of dependencies
Downloading pretty-show-1.7...
Configuring pretty-show-1.7...
Failed to install pretty-show-1.7
Build log ( /home/demo/.cabal/logs/ghc-8.2.2/pretty-show-1.7-9rjWSwh2Gh5B6UEzHKZ51C.log ):
cabal: Entering directory '/tmp/cabal-tmp-22829/pretty-show-1.7'
Configuring pretty-show-1.7...
cabal: The program 'happy' is required but it could not be found.
cabal: Leaving directory '/tmp/cabal-tmp-22829/pretty-show-1.7'
-- continues with more dependencies
cabal: Error: some packages failed to install:
accelerate-1.2.0.0-5xX8hkKbJU3BsvpnfwK9BZ depends on accelerate-1.2.0.0 which
failed to install.
accelerate-llvm-1.2.0.0-Ee8W31DRuuQKwkQk3WblO6 depends on
accelerate-llvm-1.2.0.0 which failed to install.
accelerate-llvm-native-1.2.0.0-9uprijIyAPq889dHLbzG5Q depends on
accelerate-llvm-native-1.2.0.0 which failed to install.
hedgehog-0.5.3-A0rVPRnfqexltWfrBghot depends on hedgehog-0.5.3 which failed to
install.
pretty-show-1.7-9rjWSwh2Gh5B6UEzHKZ51C failed during the configure step. The
exception was:
ExitFailure 1
tasty-hedgehog-0.2.0.0-IWSq34biPkh1eM4D81CNAy depends on
tasty-hedgehog-0.2.0.0 which failed to install.

WORKARROUND: install happy before even trying.

**Comment by yav** [comment]
Hi, thanks for letting me know.  This looks like an issue with `cabal`.   When a library depends on an external executable (e.g., `happy` in this case), `cabal` gives an error, saying what is missing, but does not attempt to install this executable automatically.   Newer versions of Cabal have some support for doing such installs, but that appears to work only when using "new style" builds, while "traditional" builds still have the old behavior.
