### ISSUE TITLE
ppsh breaks on `intervals`

### ISSUE THREAD

**Issue by dspies-leapyear** [yav/pretty-show#33]
`Numeric.Interval.Interval` objects from the intervals package when shown have the representation `(a ... b)`
http://hackage.haskell.org/package/intervals-0.8.1/docs/Numeric-Interval.html

Passing any object containing intervals as an argument into `ppsh` causes it to just output the same string with no formatting applied:

```
$ echo "thisisareallylongnamethatgoesonandonsoitneedstobelinewrappedwhencombinedwith ... thisnamerightherewhichisalsoreallylongandyoureprobablytiredoftryingtoread" | ppsh
thisisareallylongnamethatgoesonandonsoitneedstobelinewrappedwhencombinedwith ... thisnamerightherewhichisalsoreallylongandyoureprobablytiredoftryingtoread
```

**Comment by yav** [comment]
Thanks for reporting this.  I relaxed the grammar to allow unconventional infix operators, so hopefully you'll get slightly better output.   The new version is 1.9.2 on Hackage.
