### ISSUE TITLE
Special case parsing for times and dates

### ISSUE THREAD

**Issue by expipiplus1** [yav/pretty-show#38]
Sadly the `Show` instance for many types in the `time` library are not valid haskell, and are instead a human readable time. It would be nice if pretty show didn't mangle these :)

```haskell
*Data.Time> print midday
12:00:00
*Data.Time> pPrint midday
12 : 00 : 00
*Data.Time> print =<< getCurrentTime
2019-02-12 09:16:19.694870534 UTC
*Data.Time> pPrint =<< getCurrentTime
2019 (-02) (-12) 09 : 16 : 22.663191995 UTC
```

**Comment by yav** [comment]
Hi, we already go through some efforts to make times more or less readable.  The latest version of `pretty-show` (1.9.5 on hackage) looks like this:

```Haskell
> pPrint =<< getCurrentTime
(2019 - 02 - 12) (19 : 20 : 03.397005377) UTC
```

**Comment by expipiplus1** [comment]
Oh great! Thanks.
