### ISSUE TITLE
prettyprint UTCTime violates read . ppShow = id

### ISSUE THREAD

**Issue by andrewufrank** [yav/pretty-show#39]
The current handling of UTCTime produces  
   `(2012 - 08 - 09) (10 : 54 : 00) UTC`
which is not readable with `read`. The standard show for UTCTime is 
    `2012-08-09 10:54:00 UTC`
which would be ok as prettyprinted - it looks  human readable to me. 

I looked in the code, but could not see where the conversion is done, therefore I have no suggestion how to change. Perhaps it would be useful to add a generic mechanism where a datatype can be excluded (even when burried deep in a datatructure which should be prettyprinted); wrapping the data type into another type would not help when it is deep in a list or record, which is prettyprinted and calls recursively `ppShow`.

**Comment by yav** [comment]
I don't think `read . ppShow  = id` is a law we can achieve as there is no way for `pretty-show` to know how the `Read` instance for a type works.   In general, `pretty-show` works well with `Show` instances that follow Haskell's lexical syntax, and we do a best effort to do something sensible in other cases---producing that---more or less--readable instance for `time` really took some hacking :-)

**Comment by andrewufrank** [comment]
Sorry for not having stated that I mean only Read instances produced by Haskell correspoding to Show instances following the haskell rules. 
I am wondering why it was difficult to produce this special crafted ppShow when the standard show would be readable enough. Can you point me to the code so I can understand better what is going on. 
Thank you for an otherwise very usable tool!

**Comment by yav** [comment]
Well, I started to write a response to explain why it would be hard to do, and then it occurred to me that
maybe that's not actually the case, at least for some of the common date/times :-) 

So I just pushed another version that should handle some of these (version 1.9.6 on Github).  Could you give it a go and let me know if it seems to work for your use case?

Unfortunately, I haven't had time to setup a test suite, so I hope I didn't break something else.

**Comment by andrewufrank** [comment]
takes a day or so to get around to test, but will do! Thank you!

**Comment by andrewufrank** [comment]
I tested it and it works perfectly - thank you ! I looked at the code, but did not fully understand ... but it works as expected. When will you push to hackage? can you tell me, to remove the link to my cloned version.
