### ISSUE TITLE
Allow quasi-quotes? Related to date/time rendering.

### ISSUE THREAD

**Issue by jacobstanley** [yav/pretty-show#40]
I tend to follow the rule that `Show` should valid Haskell lexical syntax, I guess you agree given the existence of this package! The fact that this means, assuming it's also valid abstract syntax, you can paste the result of `Show` in to your source code or GHCi and just start using the output as a value is very convenient. As such the `Show` instance for `UTCTime` is very problematic, even if `pretty-show` was able to render it nicely, as I see you've been working on.

I often `newtype` `UTCTime` to fix the render but, copy/paste is another matter, so I have been wondering if you would consider accepting a PR with (or implementing yourself) support for quasi-quote syntax?

This would allow something like below that could be pasted directly in to an editor:
```haskell
Record {
    someField = 10
  , someTime = [time|2019-06-28 09:03:29.123456789|]
  }
```

Oh and while I'm here, thanks very much for writing this package! It may well be my favourite library on Hackage :grinning:  It's the cornerstone of Hedgehog's diff output functionality.

**Comment by yav** [comment]
Thanks for the pull request---I just merged it in, and updated the dependencies to use the latest lexer.  The new version, 1.10 should be on Hackage.

**Comment by jacobstanley** [comment]
Thank you very much! Can't wait to start using it :tada:
