### ISSUE TITLE
pretty-show 1.5 won't build with GHC 7.0.4

### ISSUE THREAD

**Issue by peti** [yav/pretty-show#5]
Hi,

I get the following error trying compile your package with GHC 7.0.4:

    Building pretty-show-1.5...

    Text/Show/PrettyVal.hs:3:14:
        Unsupported extension: DefaultSignatures

Is there any chance that this error can be remedied? It would be nice, IMHO, to have support for all ghc 7.x releases.

**Comment by yav** [comment]
This should be fixed with the flag, but I don't have an installation to test it.  Please re-open if there is still an issue, and I'll have a look at it again.
